Added slog to OmniPaxos.
haraldng/omnipaxos pull request #16
Opened 2021-08-09 14:48 UTC by Nightcro

Please make sure these boxes are checked, before submitting a new PR.

- [x] You ran `rustfmt` on the code base before submitting (on latest nightly with rustfmt support)
- [x] You reference which issue is being closed in the PR text (if applicable)

## Issues

Fixes #3 
Added slog crate as default logger for the omnipaxos system.

## Breaking Changes

There's no rotation or compression of the log file. The log file grows until all space is consumed.

## Other Changes

Added the option for the user to add their own implementation of logger based on slog.
The default logger outputs to terminal and file.

Start by giving a bullet list overview (for later inclusion in the release notes), before describing the details, if necessary.

2021-08-09 19:52 UTC, haraldng requested changes

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +            let l = if let Some(log) = logger {
use `unwrap_or_else ` instead to be more concise.

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +            info!(self.logger, "Initiate new heartbeat round");
```suggestion
            trace!(self.logger, "Initiate new heartbeat round");
```
Also include the round

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +            info!(self.logger, "Heartbeat timeout");
Again use `trace!` and round number.

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +                    "Majority confirmed, size: {}",
```suggestion
                    "Received a majority of heartbeats, size: {}",
```

Log `self.ballots` instead of just the size.

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
>              let result: Option<Leader<Ballot>> = if self.ballots.len() + 1 >= self.majority {
I think it makes sense to have a `warn!` that logs `self.ballots` when we don't receive a majority

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +                HeartbeatMsg::Reply(rep) => self.handle_reply(m.from, rep),
remove `m.from`. If we are using it only for logging, we can simply log the ballot in `rep`.

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +        fn handle_reply(&mut self, from: u64, rep: HeartbeatReply) {
remove the `from` parameter and simply log the ballot.

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +                info!(self.logger, "New Leader elected, pid: {}", top_pid);
```suggestion
                debug!(self.logger, "New Leader elected, pid: {}", top_pid);
```

log leader's ballot as well.

2021-08-09 19:52 UTC, haraldng commented on src/paxos.rs
> +        info!(self.logger, "Connection lost pid {}", pid);
```suggestion
        debug!(self.logger, "Connection lost to pid: {}", pid);
```

2021-08-09 19:52 UTC, haraldng commented on src/paxos.rs
> +        debug!(self.logger, "Clear peers state");
Remove this, it's not very interesting.

2021-08-09 19:52 UTC, haraldng commented on src/paxos.rs
> +        info!(self.logger, "Replica selected as leader");
```suggestion
        debug!(self.logger, "Replica got elected as the leader");
```

Also log the round

2021-08-09 19:52 UTC, haraldng commented on src/paxos.rs
> +            info!(self.logger, "Forwarding proposal to Leader {}", self.leader);
```suggestion
            trace!(self.logger, "Forwarding proposal to Leader {}", self.leader);
```

2021-08-09 19:52 UTC, haraldng commented on src/paxos.rs
> +        debug!(self.logger, "Incoming Forwarded Proposal");
```suggestion
        trace!(self.logger, "Incoming Forwarded Proposal");
```

2021-08-09 19:52 UTC, haraldng commented on src/paxos.rs
> +        debug!(self.logger, "Incoming message Accepted {}", from);
```suggestion
        trace!(self.logger, "Incoming message Accepted {}", from);
```

2021-08-09 19:52 UTC, haraldng commented on src/paxos.rs
> +        debug!(self.logger, "Incoming message Accept Decide");
```suggestion
        trace!(self.logger, "Incoming message Accept Decide");
```

2021-08-09 19:52 UTC, haraldng commented on src/paxos.rs
> +        debug!(self.logger, "Incoming message Decide");
```suggestion
        trace!(self.logger, "Incoming message Decide");
```

2021-08-09 19:52 UTC, haraldng commented on src/util.rs
>  use crate::leader_election::Round;
Now that we are creating a utils module for config... (see [comment](https://github.com/haraldng/omnipaxos/pull/17#discussion_r685451326) for #17), We might as well move this to `utils/logger.rs`

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +                debug!(self.logger, "Initial heartbeat delay");
```suggestion
                debug!(self.logger, "Using initial heartbeat delay");
```

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +            debug!(self.logger, "Heartbeat request from {}", from);
```suggestion
            trace!(self.logger, "Heartbeat request from {}", from);
```

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
> +            debug!(self.logger, "Heartbeat reply from {}", from);
```suggestion
            trace!(self.logger, "Heartbeat reply from {}", from);
```

2021-08-09 19:52 UTC, haraldng commented on src/leader_election.rs
>              } else {
log with `warn!` if we get a late response. It should log the current round, the ballot and `self.hb_current_delay`

2021-08-10 10:25 UTC, haraldng commented
Can you also remove the section on "Breaking Changes" (as it is not a breaking change) and make an issue of it instead?

2021-08-10 11:12 UTC, haraldng requested changes

2021-08-10 11:12 UTC, haraldng commented on src/leader_election.rs
> +                debug!(
move `self.hb_round += 1` to above here instead before the logging. Then we don't have to do the confusing and possibly dangerous thing of logging something that is not actually the value with +1.

2021-08-10 11:12 UTC, haraldng commented on src/leader_election.rs
>              debug!(self.logger, "Current heartbeat round: {}", self.hb_round);
This can probably be removed, sorry for changing my mind :)

2021-08-10 11:49 UTC, Nightcro commented
Also Fixes #18

2021-08-10 12:17 UTC, haraldng approved these changes

2021-08-10 12:17 UTC, merged