Add Ballot Leader Election module and a Memory Storage
haraldng/omnipaxos pull request #9
Opened 2021-07-09 12:54 UTC by Nightcro

Please make sure these boxes are checked, before submitting a new PR.

- [x] You ran `rustfmt` on the code base before submitting (on latest nightly with rustfmt support)
- [x] You reference which issue is being closed in the PR text (if applicable)

## Other Changes

Ported Ballot Leader Election using tick() as a timer.
Ported MemoryStorage

Signed-off-by: Nightcro <alexandru20059@gmail.com>

2021-07-09 15:14 UTC, haraldng requested changes
Most of it is about docs and naming. However, please take a closer look at `tick()` again (or let me know if I have misunderstood the intended usage for it).

2021-07-09 15:14 UTC, haraldng commented on src/ble/ballot_leader_election.rs
> +    leader: Option<Ballot>,
I think the user should be able to read who is the current leader at any time. So let's create a public function `get_leader()` that returns this.

2021-07-14 08:25 UTC, haraldng requested changes
Some more comments on docs and some small issues in BLE.

2021-07-14 08:29 UTC, haraldng commented on src/leader_election.rs
> +
We must have a public function that returns the outgoing messages. We implemented one in the integration tests. The documentation should be similar to tick() that asks the user to call it repeatedly.

2021-07-21 13:56 UTC, Nightcro commented
Fixes #11

2021-08-02 14:16 UTC, haraldng requested changes

2021-08-02 15:03 UTC, Nightcro commented on src/leader_election.rs
> +        _hb_current_delay: u64,
I wasn't sure, how to state that this was an internal variable, not to be seen by the user
I can remove the underscore

2021-08-02 15:12 UTC, haraldng commented on src/leader_election.rs
> +        _hb_current_delay: u64,
Yes, remove the underscore. I think it should be private by default if you don't have `pub` before the variable

2021-08-02 15:50 UTC, merged