Doc structure checker
haraldng/omnipaxos pull request #95
Opened 2023-05-20 10:02 UTC by TimXLHan

- [x] You ran the local CI checker with `./check.sh` with no errors
- [x] You updated the OmniPaxos book (if applicable)

## Issues

This PR is about omnipaxos documentation structure management.

## Breaking Changes

- Changed the docs file structure to be consistent with website.
- Added doc updating guideline in `how-to-contribute`
- Added doc structure checker script file in `.github/scripts`
- Added doc structure check workflow in `ci.yml`

2023-05-22 10:04 UTC, haraldng requested changes
Please check if it's possible to do the checks without Javascript. I'll also update the `how-to-contribute.md` before merging.

2023-05-22 10:04 UTC, haraldng commented on .github/scripts/doc_structure_checker.js
Would it be possible to have this as a batch script? Because it would be nice if we could include it in the `check.sh` without Javascript dependency.

2023-05-22 14:57 UTC, TimXLHan commented on .github/scripts/doc_structure_checker.js
Yes I have tried to interpret it in to sh script, only thing is it will make the code unreadable, is it matter?

2023-05-22 15:06 UTC, haraldng commented on .github/scripts/doc_structure_checker.js
Yes, just add some comments in the script so we know what it does.

I would say we can create a new folder `scripts` and put it there. But keep `check.sh` in the root.

2023-05-22 18:23 UTC, haraldng commented on docs/contributing/contributing.md
> +```
Would it be possible to check this in the script as well?

2023-05-23 08:38 UTC, TimXLHan commented on .github/scripts/doc_structure_checker.js
> +        throw new Error(`Invalid document structure: 'path' property for section '${key}' must be a string`);
There is another checker to make sure that the file path is correct (i.e. try to open corresponding file using given path).
```js
function checkFilePath(filePath) {
    try {
        fs.accessSync(filePath, fs.constants.F_OK);
        return true; // File exists
    } catch (error) {
        throw new Error(`File "${filePath}" does not exist`);
    }
}
```

2023-06-11 18:25 UTC, haraldng commented
Please also try fixing the [docs action](https://github.com/haraldng/omnipaxos/blob/master/.github/workflows/push_doc_changes_to_website.yml) for the website. I tried to fix it but it still is not completely correct. If we cannot fix it, let's at least make sure it doesn't remove all docs.

2023-06-27 10:54 UTC, haraldng approved these changes

2023-06-27 10:54 UTC, haraldng commented on docs/contributing/contributing.md
> +Pull requests ise the way to make concrete changes to the code, documentation, and other things related to the OmniPaxos repository. Before implementing a new feature or a big change, please first cr
```suggestion
Pull requests are the way to make concrete changes to the code, documentation, and other things related to the OmniPaxos repository. Before implementing a new feature or a big change, please first create an issue that describes the motivation and goal of it. This enables others to give feedback and guidance that will make the PR more likely to get merged.
```

2023-06-27 10:54 UTC, haraldng commented on docs/contributing/contributing.md
> +To make a cross-reference in the documentation, please make sure to remove the ``.md`` suffix from the relative path. For instance, to make a cross-reference from `docs/omnipaxos/compaction.md` to `d
```suggestion
To make a cross-reference in the documentation, **please make sure to remove the ``.md`` suffix from the relative path**. For instance, to make a cross-reference from `docs/omnipaxos/compaction.md` to `docs/omnipaxos/logging.md`:
```

2023-06-27 10:55 UTC, haraldng commented
@TimXLHan please fix merge conflicts and this can be merged.

2023-06-28 08:59 UTC, merged